### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by nodoubtman** [khalisafkari/react-native-google-photos#12]
Hello im using npm with Raspberry Pi 3,
im getting this error.

can you help me ?

Thanks!

import {default as gb} from './dist/api';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/pi/Desktop/LG_TV/google_pic.js:1:27)

**Comment by khalisafkari** [comment]
Using the type module in package.json

You can refer to this link https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module
